git submodule add https://github.com/zlib-ng/zlib-ng
git submodule add https://github.com/Tessil/robin-map
git submodule add https://github.com/jbeder/yaml-cpp
git submodule add https://github.com/pnggroup/libpng
git submodule add https://github.com/aous72/OpenJPH
git submodule add https://github.com/libjpeg-turbo/libjpeg-turbo
git submodule add https://gitlab.com/libtiff/libtiff
git submodule add https://github.com/AcademySoftwareFoundation/Imath
git submodule add https://github.com/AcademySoftwareFoundation/openexr
git submodule add https://github.com/AcademySoftwareFoundation/OpenImageIO
git submodule add https://github.com/AcademySoftwareFoundation/OpenColorIO
git submodule add https://github.com/openssl/openssl
git submodule add https://github.com/python/cpython